package com.ecommerce.ecommerce_backend.dto;

import lombok.Data;

@Data
public class RegisterRequestDTO {
    private String name;
    private String email;
    private String password;

    // no id and no role
    // no id : auto generated by System
    // no role : default role is customer(because if not anyone can register as admin)
}
